### ISSUE TITLE
斜体不能正确显示

### ISSUE THREAD

**Issue by ldezho** [rztime/RZRichTextView#11]

**Comment by daAnMr** [comment]
NSString+RZCode文件丢失

**Comment by ldezho** [comment]
有这个文件。在textview中编辑斜体的时候是正常的。转换成html字符串保存后，再次加载这个html字符串进行显示的时候斜体没了。

**Comment by rztime** [comment]
有部分属性在富文本中支持，但是转到html时，有些css以及标签转换不过去，所以丢失，后边我会优化一下

**Comment by rztime** [comment]
> NSString+RZCode文件丢失

这个你pod update一下

**Comment by daAnMr** [comment]
好的 ，谢谢

**Comment by ldezho** [comment]
@rztime 谢谢回答，知道了。
