### ISSUE TITLE
请指教一下如何导出JavaScript的样式内容

### ISSUE THREAD

**Issue by yaodecai** [rztime/RZRichTextView#12]
使用该控件导出的都是一个html文本内容，附带了大量的标签样式，请问可以导出这种模式的内容吗？
![image](https://user-images.githubusercontent.com/23653681/71069211-375e2200-21b3-11ea-8d6b-ca0c2e9e12b1.png)

**Comment by bugaio** [comment]
代码里  是使用 原生的 attr 转html
`NSMutableArray *exclude = [NSMutableArray array];
    
     [exclude addObjectsFromArray:[NSArray arrayWithObjects:@"APPLET", @"BASEFONT", @"CENTER", @"DIR", @"FONT", @"ISINDEX", @"MENU", @"S", @"STRIKE", @"U",@"XML", nil]];
    [exclude addObjectsFromArray:[NSArray arrayWithObjects:@"doctype", @"html", @"head", @"body", nil]];

    NSDictionary *htmlAtt = [NSDictionary dictionaryWithObjectsAndKeys:
    NSHTMLTextDocumentType, NSDocumentTypeDocumentAttribute,
    exclude, @"ExcludedElements", nil];
        
    NSData *htmlData = [self dataFromRange:NSMakeRange(0, self.length) documentAttributes:htmlAtt error:nil];
    `
你可以 试一试

**Comment by bugaio** [comment]
代码 里是使用 原生的   方法, 将 attr -> html
那么,  你可以 这样试一试
```
NSMutableArray *exclude = [NSMutableArray array];
    
     [exclude addObjectsFromArray:[NSArray arrayWithObjects:@"APPLET", @"BASEFONT", @"CENTER", @"DIR", @"FONT", @"ISINDEX", @"MENU", @"S", @"STRIKE", @"U",@"XML", nil]];
    [exclude addObjectsFromArray:[NSArray arrayWithObjects:@"doctype", @"html", @"head", @"body", nil]];

    NSDictionary *htmlAtt = [NSDictionary dictionaryWithObjectsAndKeys:
    NSHTMLTextDocumentType, NSDocumentTypeDocumentAttribute,
    exclude, @"ExcludedElements", nil];
        
    NSData *htmlData = [self dataFromRange:NSMakeRange(0, self.length) documentAttributes:htmlAtt error:nil];
   
```
