### ISSUE TITLE
解析html,后，如何设置 图片的尺寸大小 iOS

### ISSUE THREAD

**Issue by Ama-SmallBoy** [rztime/RZRichTextView#13]

**Comment by rztime** [comment]
1.谁生成谁负责，比如前端统一好格式样式，再生成html，解析的时候就不需要设置图片格式样式
2.后端拉的数据，让后端配置好
如果要自己解决：
3.自己主动修改html的img标签里的style

**Comment by Ama-SmallBoy** [comment]
如果不设置，会出现按照图片本身的尺寸显示，这样，对于大图，就会出现超出屏幕显示问题



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rztime"<notifications@github.com&gt;; 
发送时间: 2020年2月16日(星期天) 上午10:04
收件人: "rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;; 
抄送: "海阔天空"<1350587807@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




1.谁生成谁负责，比如前端统一好格式样式，再生成html，解析的时候就不需要设置图片格式样式
 2.后端拉的数据，让后端配置好
 如果要自己解决：
 3.自己主动修改html的img标签里的style

**Comment by rztime** [comment]
html也涉及到大小屏屏幕适配，图片也要适配屏幕，简单的可以设置max-width：100%

**Comment by Ama-SmallBoy** [comment]
问你一个紧急问题，我们的富文本textView 的段落的默认字体大小是多少？当我使用confer.paragraphStyle.alignment(NSTextAlignmentLeft),[UIFont systemFontOfSize:17.0]; confer.appendImageByUrl(imageLink).tapAction(fileLink.rz_encodedString).paragraphStyle.alignment(NSTextAlignmentLeft),[UIFont systemFontOfSize:17.0]; 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }的时候，点击回车，就会变成 字体大小为12pt &nbsp;这个什么原因&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rztime"<notifications@github.com&gt;; 
发送时间: 2020年2月16日(星期天) 上午10:58
收件人: "rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;; 
抄送: "海阔天空"<1350587807@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




html也涉及到大小屏屏幕适配，图片也要适配屏幕，简单的可以设置max-width：100%

**Comment by Ama-SmallBoy** [comment]
如果的我想更改它的字体大小，如何更改，全局的字体大小




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"rztime"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月16日(星期天) 上午10:58
收件人:&nbsp;"rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;;
抄送:&nbsp;"海阔天空"<1350587807@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




html也涉及到大小屏屏幕适配，图片也要适配屏幕，简单的可以设置max-width：100%

**Comment by rztime** [comment]
如果不对textView.font = [UIFont systemFontOfSize:17.0];设置，那么其默认字体是12，设置confer.text(“text”).font([UIFont systemFontOfSize:17.0]),在text之后编辑字体才会是17

**Comment by Ama-SmallBoy** [comment]
图片居中的那个你知道怎么搞吗？我现在使用的是confer.paragraphStyle.alignment(NSTextAlignmentLeft),[UIFont systemFontOfSize:17.0]; confer.appendImageByUrl(imageLink).tapAction(fileLink.rz_encodedString).paragraphStyle.alignment(NSTextAlignmentLeft),[UIFont systemFontOfSize:17.0];让其居中显示。如果我修改默认字体大小，该如何修改，直接改掉的那个12，将17，作为默认字体大小？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rztime"<notifications@github.com&gt;; 
发送时间: 2020年2月18日(星期二) 下午5:17
收件人: "rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;; 
抄送: "海阔天空"<1350587807@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




如果不对textView.font = [UIFont systemFontOfSize:17.0];设置，那么其默认字体是12，设置confer.text(“text”).font([UIFont systemFontOfSize:17.0]),在text之后编辑字体才会是17

**Comment by rztime** [comment]
参考 https://github.com/rztime/RZColorful文档和demo

**Comment by Ama-SmallBoy** [comment]
你好，我想你要图片居中，使用这样confer.text(@"\n").font(rz_font(TaskRichFont)).paragraphStyle.alignment(NSTextAlignmentLeft); 
&nbsp; &nbsp; &nbsp; &nbsp; confer.appendImage(image).size(CGSizeMake(width, height), RZHorizontalAlignCenter, [UIFont systemFontOfSize:TaskRichFont]).paragraphStyle.alignment(NSTextAlignmentCenter);
 
&nbsp; &nbsp; &nbsp; &nbsp; confer.text(@"\n").font(rz_font(TaskRichFont)).paragraphStyle.alignment(NSTextAlignmentLeft);
 
&nbsp; &nbsp; &nbsp; &nbsp; confer.text(@"\n").font(rz_font(TaskRichFont)).paragraphStyle.alignment(NSTextAlignmentLeft);为什么没有效果

还有就是，我想在点击回车的时候，换成左对齐，输入，也没有效果

&nbsp;&nbsp;_textView.rz_shouldChangeTextInRange = ^BOOL(RZRichTextView * _Nonnull textView, NSRange inRange, NSString * _Nonnull replacementText) {

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if ([replacementText isEqualToString:@"\n"]) {

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; NSMutableAttributedString * attributedText = textView.attributedText.mutableCopy;

&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; NSAttributedString * tmpString = [NSAttributedString rz_colorfulConfer:^(RZColorfulConferrer *confer) {

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; confer.text(@"\n").textColor(kUIColorFromRGB(0x333333, 1.0)).paragraphStyle.alignment(NSTextAlignmentLeft),rz_font(TaskRichFont);

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }];

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; [attributedText replaceCharactersInRange:inRange withAttributedString:tmpString];

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; textView.attributedText = attributedText;

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }

&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;

&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return YES;

 

&nbsp; &nbsp; &nbsp; &nbsp; };

急等在帮忙看一下，非常感谢，拜托了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rztime"<notifications@github.com&gt;; 
发送时间: 2020年2月18日(星期二) 下午5:26
收件人: "rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;; 
抄送: "海阔天空"<1350587807@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




参考 https://github.com/rztime/RZColorful文档和demo

**Comment by rztime** [comment]
1.（文字居左，图片居中），一行（一段）文字不能使用两种对齐方式
2.你还需要设置光标位置在最后

**Comment by kyf0305** [comment]
NSAttributedString *str = [NSAttributedString htmlString:self.html];
[str enumerateAttribute:NSAttachmentAttributeName inRange:NSMakeRange(0, str.length) options:0 usingBlock:^(id  _Nullable value, NSRange range, BOOL * _Nonnull stop) {
        if (value) {
            NSTextAttachment *ment = value;
            if (ment.bounds.size.width > SCREEN_WIDTH-10) {// 设置图片宽度不超出屏幕
                CGFloat scale = (SCREEN_WIDTH-10) / ment.bounds.size.width;
                ment.bounds = CGRectMake(0, 0, scale * ment.bounds.size.width, scale * ment.bounds.size.height);
            }
        }
    }];

**Comment by Ama-SmallBoy** [comment]
字体在换行的时候，会显示成tintColor的颜色，这是怎么回事



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kyf0305"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 晚上11:46
收件人: "rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;; 
抄送: "海阔天空"<1350587807@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




NSAttributedString *str = [NSAttributedString htmlString:self.html];
 [str enumerateAttribute:NSAttachmentAttributeName inRange:NSMakeRange(0, str.length) options:0 usingBlock:^(id  _Nullable value, NSRange range, BOOL * _Nonnull stop) {
 if (value) {
 NSTextAttachment *ment = value;
 if (ment.bounds.size.width &gt; SCREEN_WIDTH-10) {// 设置图片宽度不超出屏幕
 CGFloat scale = (SCREEN_WIDTH-10) / ment.bounds.size.width;
 ment.bounds = CGRectMake(0, 0, scale * ment.bounds.size.width, scale * ment.bounds.size.height);
 }
 }
 }];

**Comment by Ama-SmallBoy** [comment]
_textView.rz_shouldChangeTextInRange = ^BOOL(RZRichTextView * _Nonnull textView, NSRange inRange, NSString * _Nonnull replacementText) {
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; //点击回车 更改 段落格式
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; if ([replacementText isEqualToString:@"\n"]) {
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; UIFont *tempfont = [UIFont systemFontOfSize:TaskRichFont];
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; NSMutableParagraphStyle * paragraphStyle = [[NSMutableParagraphStyle alloc]init];
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; paragraphStyle.alignment = NSTextAlignmentLeft;
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; selfWeak.textView.rz_attributedDictionays[NSFontAttributeName] = tempfont;
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; selfWeak.textView.rz_attributedDictionays[NSForegroundColorAttributeName] = kUIColorFromRGB(0x333333, 1.0);
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; selfWeak.textView.rz_attributedDictionays[NSParagraphStyleAttributeName] = paragraphStyle;
 
&nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; }
 
&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; return YES;
 
&nbsp; &nbsp; &nbsp; &nbsp; };

去掉段落格式的方法对吗？有时候可以去掉，有时候，去不掉，怎么回事





------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"kyf0305"<notifications@github.com&gt;;
发送时间:&nbsp;2020年2月20日(星期四) 晚上11:46
收件人:&nbsp;"rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;;
抄送:&nbsp;"海阔天空"<1350587807@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




NSAttributedString *str = [NSAttributedString htmlString:self.html];
 [str enumerateAttribute:NSAttachmentAttributeName inRange:NSMakeRange(0, str.length) options:0 usingBlock:^(id  _Nullable value, NSRange range, BOOL * _Nonnull stop) {
 if (value) {
 NSTextAttachment *ment = value;
 if (ment.bounds.size.width &gt; SCREEN_WIDTH-10) {// 设置图片宽度不超出屏幕
 CGFloat scale = (SCREEN_WIDTH-10) / ment.bounds.size.width;
 ment.bounds = CGRectMake(0, 0, scale * ment.bounds.size.width, scale * ment.bounds.size.height);
 }
 }
 }];

**Comment by rztime** [comment]
在文字改变（rz_didChangedText）之后，在去修改其属性，记得刷新工具条

**Comment by Ama-SmallBoy** [comment]
编辑器什么时候会读取光标的颜色，这边的会读取光标的颜色，并将光标的颜色设置成文本颜色，这是什么情况，我搞不懂，你能帮我解答一下吗？



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rztime"<notifications@github.com&gt;; 
发送时间: 2020年2月21日(星期五) 上午10:11
收件人: "rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;; 
抄送: "海阔天空"<1350587807@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




在文字改变（rz_didChangedText）之后，在去修改其属性，记得刷新工具条

**Comment by Ama-SmallBoy** [comment]
我能加你一下微信吗？我想找你了解一下，这个东西，帮我看看，到底是怎样的问题：






------------------&nbsp;原始邮件&nbsp;------------------
发件人: "kyf0305"<notifications@github.com&gt;; 
发送时间: 2020年2月20日(星期四) 晚上11:46
收件人: "rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;; 
抄送: "海阔天空"<1350587807@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




NSAttributedString *str = [NSAttributedString htmlString:self.html];
 [str enumerateAttribute:NSAttachmentAttributeName inRange:NSMakeRange(0, str.length) options:0 usingBlock:^(id  _Nullable value, NSRange range, BOOL * _Nonnull stop) {
 if (value) {
 NSTextAttachment *ment = value;
 if (ment.bounds.size.width &gt; SCREEN_WIDTH-10) {// 设置图片宽度不超出屏幕
 CGFloat scale = (SCREEN_WIDTH-10) / ment.bounds.size.width;
 ment.bounds = CGRectMake(0, 0, scale * ment.bounds.size.width, scale * ment.bounds.size.height);
 }
 }
 }];

**Comment by Ama-SmallBoy** [comment]
- (void)insertImage:(UIImage *)image{
 
&nbsp; &nbsp; if (!image) {
 
&nbsp; &nbsp; &nbsp; &nbsp; return ;
 
&nbsp; &nbsp; }
 
&nbsp; &nbsp; self.editing = YES;
 
&nbsp; &nbsp; CGFloat width = image.size.width;
 
&nbsp; &nbsp; CGFloat height = image.size.height;
 
&nbsp; &nbsp; if (width &gt; SCREEN_WIDTH&nbsp; - TextPaddingSpace*2 - 10) {
 
&nbsp; &nbsp; &nbsp; &nbsp; width = SCREEN_WIDTH&nbsp; - TextPaddingSpace*2 - 10;
 
&nbsp; &nbsp; &nbsp; &nbsp; height = height * width / image.size.width;
 
&nbsp; &nbsp; }
 
&nbsp; &nbsp; NSAttributedString* tmpAttributedString = [NSAttributedString rz_colorfulConfer:^(RZColorfulConferrer *confer) {
 
&nbsp; &nbsp; &nbsp; &nbsp; confer.text(@"\n").font(rz_font(TaskRichFont));
 
&nbsp; &nbsp; &nbsp; &nbsp; confer.appendImage(image).size(CGSizeMake(width, height),RZHorizontalAlignBottom, [UIFont systemFontOfSize:TaskRichFont]).paragraphStyle.alignment(NSTextAlignmentCenter);
 
&nbsp; &nbsp; &nbsp; &nbsp; confer.text(@"\n").font(rz_font(TaskRichFont)).textColor(kUIColorFromRGB(0x333333, 1.0)).paragraphStyle.alignment(NSTextAlignmentLeft);
 
&nbsp; &nbsp; &nbsp; &nbsp; //confer.text(@"\n").font(rz_font(TaskRichFont)).textColor(kUIColorFromRGB(0x333333, 1.0)).paragraphStyle.alignment(NSTextAlignmentLeft);
 
&nbsp; &nbsp; }];
 
&nbsp; &nbsp; NSMutableAttributedString * imageAttributrdString = tmpAttributedString.mutableCopy;
 
&nbsp;&nbsp; &nbsp;
 
//&nbsp; &nbsp; NSMutableDictionary *tempAttrDict = [self rz_attributesAtSelectedRange].mutableCopy; // 只有在手动改变range时，才会去重置到当前的属性
 
//&nbsp; &nbsp; tempAttrDict[NSAttachmentAttributeName] = nil;&nbsp; // 如果有图片，则删除，否则图片会覆盖当前插入的图片
 
//&nbsp; &nbsp; if (tempAttrDict) {
 
//&nbsp; &nbsp; &nbsp; &nbsp; [imageAttributrdString addAttributes:tempAttrDict range:NSMakeRange(0, imageAttributrdString.length)];
 
//&nbsp; &nbsp; }
 
&nbsp; &nbsp; NSMutableAttributedString *attr = self.attributedText.mutableCopy;
 
&nbsp; &nbsp; NSRange selectedRange = self.selectedRange;
 
&nbsp; &nbsp; [attr replaceCharactersInRange:selectedRange withAttributedString:imageAttributrdString];
 
&nbsp; &nbsp; self.attributedText = attr;
 
&nbsp; &nbsp; self.selectedRange = NSMakeRange(selectedRange.location + imageAttributrdString.length, 0);
 
&nbsp;&nbsp; &nbsp;
 
//&nbsp; &nbsp; [self becomeFirstResponder];
 
//&nbsp; &nbsp; [self textViewDidChange:self];
 
}

我这样插入图片之后，光标会停留在居中的位置，我怎么才可以，在插完图片后，光标停留在最左边，


请你在我看一下，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rztime"<notifications@github.com&gt;; 
发送时间: 2020年2月21日(星期五) 上午10:11
收件人: "rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;; 
抄送: "海阔天空"<1350587807@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rztime/RZRichTextView] 解析html,后，如何设置 图片的尺寸大小 iOS (#13)




在文字改变（rz_didChangedText）之后，在去修改其属性，记得刷新工具条

**Comment by rztime** [comment]
你可以试一下，失去焦点之后，在重新becomeFirstResponder
