### ISSUE TITLE
关于输入斜体的文字后, 导出html的问题

### ISSUE THREAD

**Issue by bugaio** [rztime/RZRichTextView#14]
在 输入 斜体的文字后,  输出 的html 并没有 斜体哦?  是我 哪里 使用的不对么?

**Comment by rztime** [comment]
这个是oc底层代码的问题，估计是对html版本的修改不太友好，我后边空了想把法完善一下吧，近段时间太忙了

**Comment by bugaio** [comment]
@rztime 我找了到了一个 解决办法,  测试了一下 , 可以
大概就是 遍历 enumerateAttribute,  然后拿到 font, 如果斜体的话, 就用fontDes 弄一个  斜体的font, 然后再生成 html
https://www.jianshu.com/p/16d066705751

**Comment by rztime** [comment]
> @rztime 我找了到了一个 解决办法, 测试了一下 , 可以
> 大概就是 遍历 enumerateAttribute, 然后拿到 font, 如果斜体的话, 就用fontDes 弄一个 斜体的font, 然后再生成 html
> https://www.jianshu.com/p/16d066705751

hello，非常感谢反馈，近期空了之后我会系统测试完善一下，在继续优化一下

**Comment by rztime** [comment]
> @rztime 我找了到了一个 解决办法, 测试了一下 , 可以
> 大概就是 遍历 enumerateAttribute, 然后拿到 font, 如果斜体的话, 就用fontDes 弄一个 斜体的font, 然后再生成 html
> https://www.jianshu.com/p/16d066705751

NSAttributedString转换html时，有部分属性系统方法不支持，所以通过代码注入style，算是曲线解决了
看[- (NSString *)rz_codingToCompleteHtmlByWeb](https://github.com/rztime/RZColorful/blob/master/RZColorfulExample/RZColorful/AttributeCore/NSAttributedString+RZHtml.h)
