### ISSUE TITLE
删除图片或撤销插入图片

### ISSUE THREAD

**Issue by UbunGit** [rztime/RZRichTextView#15]
请教一下，如果每次插入图片后我都上传服务器得到url然后保存到数组中，
这时候如果用户删除这张图片或者撤销后我该怎么去维护这个url数组呢？

**Comment by rztime** [comment]
比较友好的方式是，当用户选择提交的时候，再去上传图片，然后做url替换到富文本的处理，编辑过程中，可以不进行图片上传的操作
