### ISSUE TITLE
网络图片如何添加点击事件

### ISSUE THREAD

**Issue by sdwangxianwen** [rztime/RZRichTextView#17]
网络图片如何添加点击事件？我用的时候添加多个网络图片滑动有些许卡顿，怎么处理

**Comment by rztime** [comment]
[self.textView rz_colorfulConfer:^(RZColorfulConferrer * _Nonnull confer) {
        confer.appendImageByUrl(@"xxx").tapAction(@"didclickedImage"); // 添加点击事件
    }];
    self.textView.rzDidTapTextView = ^BOOL(id  _Nullable tapObj) {
        NSLog(@"%@", tapObj);  ///  "didclickedImage"
        return false;
    };


当在textView中添加网络图片时，是在主线程将图片下载完成之后才将其绘制在textView中，所以会造成卡顿，可以自己做一个映射，将网络图片先用本地的占位图显示，在后台把图片下载下来之后，在替换回去
