### ISSUE TITLE
demo打不开

### ISSUE THREAD

**Issue by Turnarounds** [rztime/RZRichTextView#20]
你好我下载下来demo怎么打不开

**Comment by rztime** [comment]
没问题哈，请pod install或者pod update

**Comment by Turnarounds** [comment]
好的 可以了 cocopods的原因 谢了



------------------&nbsp;原始邮件&nbsp;------------------
发件人: "rztime"<notifications@github.com&gt;; 
发送时间: 2020年9月2日(星期三) 下午4:14
收件人: "rztime/RZRichTextView"<RZRichTextView@noreply.github.com&gt;; 
抄送: "Turn around"<512172578@qq.com&gt;; "Author"<author@noreply.github.com&gt;; 
主题: Re: [rztime/RZRichTextView] demo打不开 (#20)





 
没问题哈，请pod install或者pod update
