### ISSUE TITLE
加载缓存之后，滑不动

### ISSUE THREAD

**Issue by jackliuheh** [rztime/RZRichTextView#21]
加载缓存html之后，滑不动是什么原因

**Comment by jackliuheh** [comment]
必须要删除图片才可以滑动，删除文字没有回调

**Comment by rztime** [comment]
你可以把你的html发给我看看
RZRichTextView的delegate不要用，用RZRichTextView.h里的block（如rz_didChangedText）来做回调处理

**Comment by jackliuheh** [comment]
应该说是，把服务器上的HTML加载出来修改不能滑动，本地存储是没有问题的

**Comment by jackliuheh** [comment]
> 你可以把你的html发给我看看
> RZRichTextView的delegate不要用，用RZRichTextView.h里的block（如rz_didChangedText）来做回调处理

应该说是，把服务器上的HTML加载出来修改不能滑动，本地存储是没有问题的

**Comment by jackliuheh** [comment]
> 你可以把你的html发给我看看
> RZRichTextView的delegate不要用，用RZRichTextView.h里的block（如rz_didChangedText）来做回调处理

<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 14.0px '.AppleSimplifiedChineseFont'; color: #08101a}
span.s1 {font-family: '.PingFangSC-Regular'; font-weight: normal; font-style: normal; font-size: 14.00px}
span.s2 {font-family: '.PingFangSC-Regular'; font-weight: normal; font-style: normal; font-size: 14.00px; color: #ffd167}
</style>
</head>
<body>
<p class="p1"><span class="s1">记录删了我们去哪里？我现在是<img style="max-width:98%;height:auto;" src="http://192.168.1.130/img/N20012/202012/2012011550392n1q.jpg" alt="图片缺失"><img style="max-width:98%;height:auto;" src="http://192.168.1.130/img/N20012/202012/2012011550393qx1.jpg" alt="图片缺失">用不是说了</span><span class="s2">近距离看到哪里上班</span></p>
</body>
</html>

**Comment by rztime** [comment]
你可以加一个qq交流群，580839749，我刚刚建的，看看你的代码
