### ISSUE TITLE
怎样修改文字的默认大小或者其他属性，有提供接口吗

### ISSUE THREAD

**Issue by 2641062110** [rztime/RZRichTextView#22]

**Comment by rztime** [comment]
初始化的时候你可以添加属性:

textView.rz_attributedDictionays[NSFontAttributeName] =  [UIFont systemFontOfSize:17];

你还可以添加更多的其他属性，我这里默认是黑色17号字体，你可以根据你的需求来设置，如果工具条在已加载的情况下，可以rz_reloadAttributeData刷新一下工具条

**Comment by 2641062110** [comment]
感谢您的回复，问题已解决





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: rztime <notifications@github.com&gt;
发送时间: 2020年12月2日 17:45
收件人: rztime/RZRichTextView <RZRichTextView@noreply.github.com&gt;
抄送: 2641062110 <2641062110@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[rztime/RZRichTextView] 怎样修改文字的默认大小或者其他属性，有提供接口吗 (#22)





 
初始化的时候你可以添加属性:
 
textView.rz_attributedDictionays[NSFontAttributeName] =  [UIFont systemFontOfSize:17];
 
你还可以添加更多的其他属性，我这里默认是黑色17号字体，你可以根据你的需求来设置，如果工具条在已加载的情况下，可以rz_reloadAttributeData刷新一下工具条
