### ISSUE TITLE
修改对齐方式光标位置显示错误

### ISSUE THREAD

**Issue by yuankaiJGH** [rztime/RZRichTextView#23]
不输入任何文本，修改对齐方式为居中，光标仍在最左边，输入文本后正确

这个有解决办法吗

**Comment by rztime** [comment]
这个是我的疏漏

在
RZRichTextView.m
中的
`- (void)paragraph {
...
complete:^(NSMutableParagraphStyle * _Nonnull paragraph) {
        selfWeak.rz_attributedDictionays[NSParagraphStyleAttributeName] = paragraph;
        [selfWeak rz_reloadAttributeData];
        selfWeak.textAlignment = paragraph.alignment;  // 添加这一行
    }];
}
`
你可以暂时在代码中改一下
selfWeak.textAlignment = paragraph.alignment;  // 添加这一行 即可

最近马上要过年了，有点忙，年后我在修复提交

**Comment by yuankaiJGH** [comment]
感谢回复，确认有用
