### ISSUE TITLE
超链接保存闪退和键盘遮挡问题

### ISSUE THREAD

**Issue by LiuYuZhang** [rztime/RZRichTextView#24]
1.富文本框未输入任何内容，点击超链接图标，不输内容和链接，点击“打勾”按钮直接闪退;
2.聚焦编辑框键盘被遮挡，如下图
![微信图片_20210220161201](https://user-images.githubusercontent.com/16681220/108588910-8f378080-7396-11eb-978c-a550c75b706f.jpg)

**Comment by jozdee** [comment]
+1

**Comment by rztime** [comment]
重构了一下，可以看看新的
