### ISSUE TITLE
你好，插入视频功能有思路吗？

### ISSUE THREAD

**Issue by Damsir** [rztime/RZRichTextView#26]
你好，插入视频功能有思路吗？

**Comment by rztime** [comment]
最近在重构，会加入相关的功能

大体思路就是在图片上，加一层UI，在UI上实现一些定制，最后生成html时，改成video标签

**Comment by Damsir** [comment]
好的，最近项目有这个需求，但是一直没啥思路，大概什么时候回更新这个功能呀？

**Comment by jozdee** [comment]
重构的话，可以顺便考虑下图片上面加描述

**Comment by rztime** [comment]
最近刚刚完成重构，可以下载demo看看，我的网络有点问题，暂时无法pod 1.0.0

**Comment by Damsir** [comment]
好的，谢谢啦，有时间提交一下pod哈，使用起来方便些

**Comment by Damsir** [comment]
重构之后怎么是swift的啦，有OC版本吗？

**Comment by rztime** [comment]
没写oc的，你可以用swift桥接一下

**Comment by SwiftHsw** [comment]
你好  视频现在是插入了一张图 没办法播放 我看到您写了备注
/// 在RZColorfulSwift 中提供几种转换成html的方式，如果有视频，可能需要参照codingToHtmlWithImagesURLSIfHad来实现视频的标签

如何获取视频呢？我们需求是视频和图片都有在。

**Comment by SwiftHsw** [comment]
codingToHtmlWithImagesURLSIfHad 这个方法是 替换image标签

video 呢

**Comment by rztime** [comment]
2.0.1 已支持图片（gif）、视频、音频
