### ISSUE TITLE
保存草稿出错：Incorrect NSStringEncoding value 0x8000100 detected. Assuming NSASCIIStringEncoding. Will stop this compatibility mapping behavior in the near future.

### ISSUE THREAD

**Issue by jozdee** [rztime/RZRichTextView#28]

**Comment by jozdee** [comment]
rz_codingToCompleteHtml 里面改为：

**Comment by jozdee** [comment]
rz_codingToCompleteHtml 里面改为：

**Comment by jozdee** [comment]
rz_codingToCompleteHtml 里面改为：
NSDictionary *exportParams = @{NSDocumentTypeDocumentAttribute: NSHTMLTextDocumentType,
                                   NSCharacterEncodingDocumentAttribute: @(NSUTF8StringEncoding)
    };
就可以了

**Comment by jozdee** [comment]
<!DOCTYPE html PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta http-equiv="Content-Style-Type" content="text/css">
<title></title>
<meta name="Generator" content="Cocoa HTML Writer">
<style type="text/css">
p.p1 {margin: 0.0px 0.0px 0.0px 0.0px; font: 24.0px '.AppleSimplifiedChineseFont'; color: #3e7bfa; -webkit-text-stroke: #222222}
p.p2 {margin: 0.0px 0.0px 0.0px 0.0px; font: 24.0px '.AppleSystemUIFont'; color: #3e7bfa; -webkit-text-stroke: #222222}
p.p3 {margin: 0.0px 0.0px 0.0px 0.0px; font: 24.0px '.Apple Color Emoji UI'; color: #3e7bfa; -webkit-text-stroke: #222222}
span.s1 {font-family: '.PingFangSC-Regular'; font-weight: normal; font-style: normal; font-size: 24.00px; font-kerning: none}
span.s2 {font-family: '.SFUI-Regular'; font-weight: normal; font-style: normal; font-size: 24.00px; font-kerning: none}
span.s3 {font-family: '.AppleColorEmojiUI'; font-weight: normal; font-style: normal; font-size: 24.00px; font-kerning: none}
</style>
</head>
<body>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">今天我又来了吗<span class="s2">……</span>这种情况就应该这样继续行动的计划</a></span></p>
<p class="p1"><span class="s2"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;"><br>
<span class="s1">这次还是很喜欢没有喝过奶茶</span><span class="s3">🥤</span><span class="s1">那么好看，这样就不用来上班的</span></a></span></p>
<p class="p1"><span class="s2"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;"><br>
<span class="s1">是啊我们要学会珍生态</span></a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">今天下午和同事出去逛街的路上我</a></span></p>
<p class="p1"><span class="s2"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;"><br>
<span class="s1">你说啥就</span></a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">是啊真的喜欢这个</a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">这里就是这么简单吧</a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">是因为他们在</a></span></p>
<p class="p2"><span class="s2"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;"><br>
<img style="max-width:98%;height:auto;" src="file://ArticleData/Documents/1636549217301.png" alt="图片缺失"></a></span></p>
<p class="p2"><span class="s2"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;"><br>
</a></span></p>
<p class="p1"><span class="s2"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;"><br>
<span class="s1">是的</span></a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">一个人可以去医院</a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">这里没有<span class="s2"><br>
</span>今天早上六点钟醒来的</a></span></p>
<p class="p2"><span class="s2"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;"><br>
</a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">一次我不敢再相信自己一定程度一定摇一摆了两</a></span></p>
<p class="p2"><span class="s2"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;"><br>
</a></span></p>
<p class="p3"><span class="s3"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">😊😘😘</a></span></p>
<p class="p3"><span class="s3"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">😘</a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">不过这</a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">今天</a></span></p>
<p class="p1"><span class="s1"><a  style="text-decoration: line-through underline; text-decoration-color: #00000000;-webkit-text-stroke: -0.000000px #222222FF;transform:skew(0.000000deg); transform-origin: 10 0; display:inline-block;">这么简单也要</a></span></p>
</body>
</html>

**Comment by jozdee** [comment]
新问题：草稿显示了删除线和下划线，在线用浏览器是没有删除线和下划线

**Comment by jozdee** [comment]
再有删除线或者下划线的文本后面取消下划线或删除线继续输入，输入显示没有问题，保存草稿后，加载草稿，都会显示删除线或下划线的bug

**Comment by rztime** [comment]
感谢提醒，显示删除线下划线这个bug已解决

**Comment by jozdee** [comment]
> 感谢提醒，显示删除线下划线这个bug已解决

你好，方便贴一下修复这个bug，OC的相关代码吗，我这边使用这个库有更改一些接口和方法，不好升级。

**Comment by rztime** [comment]
你先下载demo
`NSAttributedStringRZRichText.swift` 看看这个里边的`func replaceAttributes(_ attributes: [NSAttributedString.Key: Any], range: NSRange) -> NSMutableAttributedString`

这里边的方法属性，是涉及到的需要修改的

另外，在设置修改属性的时候，这些相关的属性，比如删除线style= none， 背景色阴影颜色为nil或者透明这些，也需要移除typingAttributes的属性

使用replaceAttributes的原因，是因为需要移除这些会导致bug的属性，/// RZRichtext使用，替换掉属性，部分属性如果不存在，则需要移除之前的，比如删除线等等
