### ISSUE TITLE
关于获取富文本图片的问题

### ISSUE THREAD

**Issue by meilbn** [rztime/RZRichTextView#29]
首先感谢作者开源了这个库

使用中发现一个问题，就是导出了带图片的 html 文本之后，后续修改（也就是加载了 html 文本），获取图片数组，还是会返回上传过的图片，有没有一个方法，可以过滤掉已上传的图片，只返回用户编辑的时候添加的图片数据呢？

当然，替换图片为 img 标签的方法也是只替换这些图片（可能需要新增一个方法）。

这样就不用重复上传了。

希望作者能考虑一下，谢谢

**Comment by rztime** [comment]
我的方式是，给NSTextAttachment添加一个属性，包含如url，是否已经上传的标记，在html->NSAttributedString 之后，设置好图片的url，且标记为已上传，之后编辑过程中/完成之后，在按条件判断是否需要重传，最后在转换到html时，直接拿url加进去
