### ISSUE TITLE
有没有办法在输出html时设置段落间距，行距？以便后续进一步排版

### ISSUE THREAD

**Issue by cxycxy1111** [rztime/RZRichTextView#4]
有没有办法在输出html时设置段落间距，行距？以便后续进一步排版

**Comment by rztime** [comment]
可以设置，后续版本将更上

**Comment by ffzf** [comment]
有没有可以添加链接的方法

**Comment by rztime** [comment]
> 有没有可以添加链接的方法

 (文字/图片)[链接] 涉及到文字（及其属性）图片的修改，或者链接的修改，还有删除，也就是编辑的这一套有点复杂，后边空了我会尝试更上去，但是现在不行，只能外部注入链接文字的方法，这个可以通过插入带URL的NSAttributeString到文本框字符中去来实现
