### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by wuWeiFeng2** [rztime/RZRichTextView#40]
pod之后发现是oc版本，然后手动导入，但是调用attr.rz.images()这个方法的时候，编译不通过，希望大佬看一下
<img width="831" alt="image" src="https://user-images.githubusercontent.com/18319838/174992337-a16c1412-c2a0-4c0d-a517-5c5fc0474a93.png">

**Comment by rztime** [comment]
如果需要使用，就直接下载源码，改改UI自行设置一下吧，因为UI太难统一了，所以自己处理一下吧

这个地方把UITextView改成UIView就可以了
