### ISSUE TITLE
选择多张图片后，不输入文字的话，上下没有间距。

### ISSUE THREAD

**Issue by Ryan0520** [rztime/RZRichTextView#44]
效果如下
![Simulator Screen Recording - iPhone 8 - 2023-07-06 at 23 24 42](https://github.com/rztime/RZRichTextView/assets/11271005/e2291ee2-aeeb-4c8e-a86a-28a533ac23ab)

**Comment by rztime** [comment]
如果想要一个间距，你需要设置段落样式里的行间距和段间距。
在初始化textView的时候，给typingAttributes里添加一个的NSMutableParagraphStyle.

每一行都有一个高度，文字不是把行高都占满，所以没设间距的时候，看起来也有间距。而图片是完全占满行高的，所以看起来没有间距。
