### ISSUE TITLE
请问插入视频后怎么获取带video标签的html？

### ISSUE THREAD

**Issue by ZJQian** [rztime/RZRichTextView#45]
请问插入视频后怎么获取带video标签的html？

**Comment by rztime** [comment]
参考一下图片转换成img的方法，先判断一下NSTextAttachment的附件是图片还是视频，然后用不同的标签替换

**Comment by ZJQian** [comment]
> 参考一下图片转换成img的方法，先判断一下NSTextAttachment的附件是图片还是视频，然后用不同的标签替换

好的  感谢
