### ISSUE TITLE
保存之后重新加载图片位置显示有问题

### ISSUE THREAD

**Issue by GeorgeKiki** [rztime/RZRichTextView#47]
保存导出的 code2html 字符串，使用html2Attributedstring 重新加载编辑时，图片位置及大小不能正常显示，尤其是文本字数比较多之后在文字后面添加图片，重新显示的图片会覆盖在文字上面，但是文字后面的图片正常显示位置有留白，又说明图片本身位置计算没有问题，但是显示的时候却覆盖在文本上了，当我点击编辑框开始编辑之后图片显示又恢复了正常，请问下这是什么原因导致的。

**Comment by rztime** [comment]
这个可能得原因是scrollview的contentsize不是正确的，导致textView计算图片位置错误
1.先检查一下初始化textView时，frame的宽度是否正确设置
2.在textView的contentSize改变之后，可以刷新一下(fixAttachmentInfo)

**Comment by rztime** [comment]
2.0.1版本优化了
