### ISSUE TITLE
设置textLists后, 光标位置有问题

### ISSUE THREAD

**Issue by BJGX** [rztime/RZRichTextView#48]
大佬, 设置textLists后, 原生的textView就是有这个问题 光标无法跟随最后一个文字后面

**Comment by rztime** [comment]
我这边没遇到这个问题，你可以把你的相关代码贴出来我看看吗？

**Comment by BJGX** [comment]
我没有改任何的代码, 只是设置
var img: UIImage?
        switch type {
        case .t_ol:
            mutablePara.textLists = btn.isSelected ? rz_ol : []
            img = toolImage(type: .t_ol)
        case .t_ul:
            mutablePara.textLists = btn.isSelected ? rz_ul : []
            img = toolImage(type: .t_ul)
        default: break
        }
        self.viewModel.textView?.typingAttributes[.paragraphStyle] = mutablePara
这个就会出现

原生也是这个问题, 我不知为什么

**Comment by BJGX** [comment]
这个问题真机才有, 模拟器正常的, 可以的话, 麻烦大佬, 看下这个视频https://github.com/BJGX/Image/blob/master/%E6%9C%AA%E5%91%BD%E5%90%8D.mov

**Comment by rztime** [comment]
我检查了一下，这应该是系统的bug，暂时无法解决

**Comment by rztime** [comment]
2.0.1版本 已解决
