### ISSUE TITLE
默认工具栏图片不显示

### ISSUE THREAD

**Issue by doubleGang** [rztime/RZRichTextView#5]
使用pod安装之后，默认工具栏的上的图片加载不出来

**Comment by rztime** [comment]
如果在podfile中有use_frameworks!，如果不必要，可以先注释掉，之后我会再完善一下

**Comment by doubleGang** [comment]
嗯呢，你已经做得很好了👍👍👍。
有个建议，就是当有 选中的  text 的时候，点击下面的属性功能按钮，应该让 选中的 text 发生相应的变化；这样就更好了💪💪💪。
