### ISSUE TITLE
添加输入文字背景颜色问题

### ISSUE THREAD

**Issue by qingchengl** [rztime/RZRichTextView#50]
给文字添加背景颜色，输入换行后，输入框整行的颜色都会变成文字的背景色
![Simulator Screenshot - iPhone 15 - 2023-11-24 at 08 48 45](https://github.com/rztime/RZRichTextView/assets/22407813/d55dcabe-05e6-4b4e-9806-8a6a1b8d0eb7)

**Comment by rztime** [comment]
没毛病，是这样的，换行不是以最后一个字的位置结束，是以整行结束的，你可以
`<p style="background-color: red;"> </p><p style="background-color: red;">哈哈哈</p>`
在web网页上试试
