### ISSUE TITLE
无法显示hr标签样式和无法导出斜体标签

### ISSUE THREAD

**Issue by noname004** [rztime/RZRichTextView#51]
hr标签显示不出来，全斜体的富文本 导出的html字符串 中文字符会丢失斜体标签

**Comment by rztime** [comment]
你提到的问题都存在，斜体这个已修复。

在手机上，NSAttributedString里支持的属性有限，具体的可以看看"RZCss.swift", 类似“hr”、“blockquote”、“ol”、“ul”等等这些都是需要额外实现

斜体标签这个使用的是“font-style:italic;” 这种方式实现，没用到<em><i>标签，

在2.1.1版本及之前，可能会出现无法导出斜体字，因为字体不支持中文斜体，富文本里的NSFont，拿到的是普通字体
在2.1.2版本修复了这个bug，当字体不支持中文斜体时，富文本里有NSOriginFont，用这个字体覆盖NSFont，即可
