### ISSUE TITLE
开放自定义资源下载的逻辑 （新功能请求）

### ISSUE THREAD

**Issue by FoneG** [rztime/RZRichTextView#56]
首先非常感谢作者开源这个富文本编辑器。

目前我公项目的图片等资源，并非直接根据url下载。而是根据指定的bucket和对应的id进行请求下载。所以希望作者能开放自定义资源下载的逻辑。另外，当图片/视频资源上传后，能否同步设置资源的分辨率。有助于在资源未下载成功前占位图的展示。

希望作者能支持，再次感谢~

**Comment by rztime** [comment]
你好！所有功能都是开放的。
你说的功能是可以自定义实现的。
你可以查看howtousedemo.swift里，第一行注册自定义的遮罩view，然后实现下边自定义遮罩view的回调，view内部的实现方法可以参考默认view的设置方式

**Comment by FoneG** [comment]
感谢解答。不过 RZAttachmentInfo 里面似乎没有提供资源分辨率的信息

**Comment by FoneG** [comment]
![Uploading 截屏2024-07-22 19.05.23.png…]()

**Comment by FoneG** [comment]
<img width="780" alt="截屏2024-07-22 19 05 42" src="https://github.com/user-attachments/assets/3129a8fa-de9e-4c0c-a2e2-f555da259053">

**Comment by FoneG** [comment]
<img width="1091" alt="截屏2024-07-22 19 05 23" src="https://github.com/user-attachments/assets/94545b40-09bc-4cc7-8ded-c810f7742e4a">

**Comment by rztime** [comment]
有两种方式可以解决，
第一种是设置html2Attributedstring(html: String?)，拿到Attr之后，在将其中的所有的附件取出来，重新获取一次图片，然后调用fix(attachment)，也就是上边第一张图的方法，在设置富文本之后你需要再获取一次附件然后重新设置。

第二种就更简单，把需要使用到的方法完全复制一份到你的项目，改个新方法名字，将对应的逻辑修改完善后，使用新方法即可

**Comment by FoneG** [comment]
我没有很熟练的掌握swift，虽然很冒昧，但您可以在闲暇之余增加这个功能吗  🙏🏻

**Comment by ezClip** [comment]
有同样的需求，希望作者能扩展<自定义资源下载>相关的功能

**Comment by rztime** [comment]
@FoneG @ezClip 

2.2.0 新版本已经加上了资源自定义下载的逻辑。可以查看HowToUseDemo里，将相关代码实现即可
