### ISSUE TITLE
插入图片错误

### ISSUE THREAD

**Issue by YaoWeiCheng** [rztime/RZRichTextView#6]
当插入多张图片后，从多张图片中间或第一张插入图片时，插入的图片都会与上一张图片(A)相同，而且之后无论选择哪张图片插入都是只显示A图片相同

**Comment by rztime** [comment]
> 当插入多张图片后，从多张图片中间或第一张插入图片时，插入的图片都会与上一张图片(A)相同，而且之后无论选择哪张图片插入都是只显示A图片相同

感谢反馈，已经修复
