### ISSUE TITLE
缺少文件

### ISSUE THREAD

**Issue by zhangshaoyue** [rztime/RZRichTextView#7]
您好,:
 缺少 rz_images 方法
 例如: NSArray *array = [string rz_images];

**Comment by rztime** [comment]
> 您好,:
> 缺少 rz_images 方法
> 例如: NSArray *array = [string rz_images];

请pod update一下哈，可能是你本地版本比较老

**Comment by zhangshaoyue** [comment]
好的，我试一下，感谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: rztime <notifications@github.com&gt;
发送时间: 2019年11月11日 10:38
收件人: rztime/RZRichTextView <RZRichTextView@noreply.github.com&gt;
抄送: zhangshaoyue <120016882@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[rztime/RZRichTextView] 缺少文件 (#7)



 
您好,:
 缺少 rz_images 方法
 例如: NSArray *array = [string rz_images];
  
请pod update一下哈，可能是你本地版本比较老
