### ISSUE TITLE
使用过程中经常会报这样的约束警告

### ISSUE THREAD

**Issue by theHeroisBack** [rztime/RZRichTextView#8]
<img width="1135" alt="截屏2019-11-20下午3 02 04" src="https://user-images.githubusercontent.com/30762999/69216282-ce30c200-0ba6-11ea-872a-106a904d5fc3.png">

测试了一下发现，在textVIew 正在编辑（有键盘输入的情况下），屏幕轻微左滑一下，但是不退出这个页面，这个时候就会出现这个警告

**Comment by rztime** [comment]
我看看

**Comment by rztime** [comment]
这个是系统的约束可能出现的问题，与我这份代码无关联，没什么影响，可以不用管
