### ISSUE TITLE
不知什么原因和此库一起使用时自定义的工具条cell无法注册成功

### ISSUE THREAD

**Issue by theHeroisBack** [rztime/RZRichTextView#9]
<img width="799" alt="截屏2019-11-20下午5 01 46" src="https://user-images.githubusercontent.com/30762999/69224456-8ebea180-0bb7-11ea-993b-765c111e23c8.png">

就是和这个库配合使用的时候，richTextVIew的cellForItemAtIndePath回调不会调用，无法使用自定义的cell

**Comment by rztime** [comment]
我看看到

**Comment by rztime** [comment]
self.textView.placeholder = @"测试"; 在设置placeholder时，
直接调用了这个方法
- (UITextView *)placeholderTextView {
    UITextView *textView = objc_getAssociatedObject(self, @selector(placeholderTextView));
    if (!textView) {
        NSAttributedString *originalText = self.attributedText;
        self.text = @" "; // lazily set font of `UITextView`.
        self.attributedText = originalText;

        textView = [[UITextView alloc] init];
        textView.backgroundColor = [UIColor clearColor];
        textView.textColor = [self.class defaultPlaceholderColor];
        textView.userInteractionEnabled = NO;
        textView.isAccessibilityElement = NO;
        objc_setAssociatedObject(self, @selector(placeholderTextView), textView, OBJC_ASSOCIATION_RETAIN_NONATOMIC);

        self.needsUpdateFont = YES;
        [self updatePlaceholderTextView];
        self.needsUpdateFont = NO;

        [[NSNotificationCenter defaultCenter] addObserver:self
                                                 selector:@selector(updatePlaceholderTextView)
                                                     name:UITextViewTextDidChangeNotification
                                                   object:self];

        for (NSString *key in self.class.observingKeys) {
            [self addObserver:self forKeyPath:key options:NSKeyValueObservingOptionNew context:nil];
        }
    }
    return textView;
}
在这一行：self.text = @" "; 设置text的时候，会调用
1 [UITextView setText:]
2 [UITextView textInputDidChangeSelection:]
3 [RZRichTextView textViewDidChangeSelection:]
3方法里会初始化kinputAccessoryView，而此时RZRichTextView还没有配置完，所以你要搭配使用的话，请在所有方法配置完之后，在设置textView的placeholder

**Comment by theHeroisBack** [comment]
@rztime 好的明白，另外有个问题想问一下，如果想实现编辑一半的情况下做本地缓存，在已经插入了图片的情况下，只能把图片上传至服务器得到url之后转成html字符串存储到本地吗？我意思是能不能不上传图片就把编辑一半的内容存储到本地，下次接着编辑

**Comment by rztime** [comment]
可以，你把图片的保存到沙盒中，获取到相对路径，然后将其当做url，传入到rz_codingToHtmlWithImageURLS这里边，但是NSHomeDirectory()是变化的，所以这个地方你可以用一串特殊字符串替换，然后在拿到html的时候，将其全文替换成NSHomeDirectory()；
比如
url = "file://rzrichtextviewimageurlbynshomedirectory/Documents/test.png"
NSString *html = [NSString stringWithFormat:@"<img src='file://rzrichtextviewimageurlbynshomedirectory/Documents/showmore@2x.png'>"];
        html = [html stringByReplacingOccurrencesOfString:@"rzrichtextviewimageurlbynshomedirectory" withString:NSHomeDirectory()];
NSHomeDirectory()];

**Comment by theHeroisBack** [comment]
@rztime 好的谢谢，我试一下

**Comment by theHeroisBack** [comment]
@rztime hello，我又来了😂我按照你的说法试了一下，我从本地拿到存储的html字符串以后，把那段特殊字符串全部替换掉了，然后出来的路径是：

<img width="1168" alt="oiboibu" src="https://user-images.githubusercontent.com/30762999/69440930-aac36e00-0d84-11ea-944d-baf0bb8541fd.png">

我把html转成NSAttributedString放到richTextView上以后没有显示出来；但是我用NSFileManager可以通过这个路径拿到这张图片，我也在沙盒里看了，图片确实也在，请问这可能是哪里导致的问题呢？

**Comment by rztime** [comment]
NSString *url = @"file://xxx/Documents/showmore@2x.png";
NSString *html = [attr rz_codingToHtmlWithImagesURLSIfHad:@[url]];
html = [html stringByReplacingOccurrencesOfString:@"xxx" withString:NSHomeDirectory()];
这一句转换过来，在src中，src="file:///var/...“ 你少了一个”/“

**Comment by theHeroisBack** [comment]
@rztime 好的，已经解决啦谢谢！！
另外想问一下，可以设置字间距吗？我意思不是加到rz_attributeItems里的新功能，我想设置成写死的字间距，我在这里设置 了字间距，输入的时候是有字间距的，但是当我转成html缓存到本地，再次进来转成attributedText的时候，字间距的属性消失了，是跟转成html有关吗？？

**Comment by theHeroisBack** [comment]
图片没传上去，就是在这里设置了字间距
<img width="787" alt="截屏2019-11-25下午4 39 43" src="https://user-images.githubusercontent.com/30762999/69525170-7c22de80-0fa2-11ea-8f96-187be9079cc3.png">
